seed: 1337
device: "cpu"
ipfe:
  prime: 4590007
  encryption_length: 9
data:
  name: "MNIST"
  root: "./data"
  batch_size: 64
  num_workers: 2
  download: true
  max_test_samples: 2 #000 # Limit test set to first N samples (None for all samples)
model:
  name: "ipfe" # "plain" for plain and "ipfe" for IPFE
  in_channels: 1
  num_classes: 10
  c1: 16
  c2: 32
  c3: 64
  k1: 3 
  k2: 3
  k3: 3
  dropout: 0.5
optimizations:
  precrypted: true           # default behavior of IPFECNN.forward()
  optimized_ipfe: true       # set true to use optimized IPFE (needs to be true for all following optimizations)
  kernel_parallelization: false       # set true to use kernel parallelization
  kernel_patches_parallelization: false
  batch_parallelization: true
  batch_kernels_parallelization: false
train:
  epochs: 3
  lr: 0.0005
  optimizer: "adam"
  print_every: 200      # batches
save:
  out_dir: "results"
  run_name: "mnist"
