seed: 1337
device: "cpu"
ipfe:
  prime: 6285761
  encryption_length: 4 #2x2 -> 4 #3x3 -> 9 #5x5 ->25
data:
  name: "MNIST"
  root: "./data"
  batch_size: 64
  num_workers: 2
  download: true
  max_test_samples: #000 #Limit test set to first N samples (None for all samples)
model:
  name: "plain"  # "plain" for plain and "ipfe" for IPFE
  in_channels: 1
  num_classes: 10
  c: [8, 16, 32, 64]
  k: [2, 3, 3, 3]
  p: [0, 1, 1, 1] # 1 for you use pooling. 0 for not # standard is to just have all 1
  stride: [3, 1, 1, 1]
  padding: [1, 1, 1, 1]
  dropout: 0.5
optimizations:
  precrypted: true           # default behavior of IPFECNN.forward()
  kernel_parallelization: false       # set true to use kernel parallelization
  kernel_patches_parallelization: false
  batch_parallelization: false
  batch_kernels_parallelization: true
train:
  epochs: 3
  lr: 0.0005
  optimizer: "adam"
  print_every: 200      # batches
save:
  out_dir: "results"
  models_dir: "models"
